### ISSUE TITLE
Feature request: Tree (relational) display in Firebase with the text attached.

### ISSUE THREAD

**Issue by ballio001** [flamelink/flamelink#104]
In our project we use this relational tree to read tags from another schema but it would've been a lot more convenient to show the "tag" or the text displayed itself than the id that is just a bunch of numbers.

P.S. if there is a work around i would like to know!

**Comment by coenraadf** [comment]
You can set the field to display within the tree when you set up the schema.

<img width="592" alt="Screenshot 2020-10-07 at 17 59 01" src="https://user-images.githubusercontent.com/19731120/95356306-d0873200-08c6-11eb-9c8b-d34c4e728ebe.png">

<img width="800" alt="Screenshot 2020-10-07 at 17 59 07" src="https://user-images.githubusercontent.com/19731120/95356319-d41ab900-08c6-11eb-8dbe-789f7b379058.png">

**Comment by gitdubz** [comment]
Closing this issue, not related to the SDK but rather general support.
