### ISSUE TITLE
Only the image ID is used when using the populate attribute

### ISSUE THREAD

**Issue by mfisher-fmp** [flamelink/flamelink#108]
I'm trying to use the populate attribute in the Flamelink `get()` query to populate images, as I've noticed that setting populate: true slows down the response time for the request.

I'm trying this, which was mentioned [here](https://github.com/flamelink/flamelink-js-sdk/issues/104#issuecomment-536525185):

```
const content = await flamelinkApp.content.get({
    schemaKey: page,
    populate: [{
     field: "images",
     sizes: {
       width: 1920,
       height: 999,
       quality: 1,
     },
    }],
});
```

and I have also tried:
```
const content = await flamelinkApp.content.get({
    schemaKey: page,
    populate: [{
     field: "images",
     fields: ["url"]
    }],
});
```

However, all images only return their ID. Ideally, I just want their url returned - so, the sizes attribute might not be what I'm after, but I'd just like something back when using populate for now.

Looking at the docs, it would seem I'm doing this correctly, so is there a bug in the SDK? I tried asking on StackOverflow first as I wasn't 100% sure if this is a bug or my error, but nobody responded :(.

**Comment by dewetvdm** [comment]
Hi,

Which version of the SDK are you using?

Please note the new version of the SDK is here:
https://github.com/flamelink/flamelink-js-sdk

And the documentation to be followed is here:
https://flamelink.github.io/flamelink-js-sdk/#/

**Comment by mfisher-fmp** [comment]
Hi,

I'm using `1.0.0-alpha.34`, as the new version you've linked to says it's still in development.

**Comment by dewetvdm** [comment]
The SDK does not allow you to specify which fields to populate for an image/file field

what happens if you try as an example?

```javascript
const content = await flamelinkApp.content.get({
    schemaKey: page,
    populate: {
     field: "images",
     size: { 
        width: 1920, 
        height: 999, 
        quality: 1 
    }
});
```

Replace the size with a valid size

**Comment by mfisher-fmp** [comment]
I get the same response for both of the code examples I provided - just an image ID.

What's classed as a valid size? The docs I saw said it must be within the max/min params of your image settings in Flamelink, which mine are.

_"The SDK does not allow you to specify which fields to populate for an image/file field"_ - is this mentioned in the docs anywhere?

**Comment by mfisher-fmp** [comment]
![image](https://user-images.githubusercontent.com/40168183/103665362-4012c900-4f6b-11eb-9536-5bf61e13f781.png)

This is an example of the field I'm trying to get.

**Comment by dewetvdm** [comment]
could you try 

```javascript
const content = await flamelinkApp.content.get({
    schemaKey: page,
    populate: [{
     field: "heroImages",
    }],
});
```

**Comment by mfisher-fmp** [comment]
This still didn't work in my original project. I've just spun up a test project, using the same SDK version, and it worked. Must be some issue with the original project config... how odd. 

Thanks for the help.
