### ISSUE TITLE
Permissions issue with admin app

### ISSUE THREAD

**Issue by SKLn-Rad** [flamelink/flamelink#137]
Hey all,

Hopefully a quick fix, I noticed in 1.0.0 and over, you don't have a "isAdminApp" flag on the flamelink constructor, and trying to use it raises a permissions issue.

```
export const verifyUserCreated = functions.region("europe-west1").https.onCall(
    async (data, context) => {
      await SystemService.verifyAuthenticated(context);
      
      const adminApp = admin.initializeApp();
      const flamelinkApp = flamelink({
        firebaseApp: adminApp,
        dbType: "cf",
        precache: false,
        env: data.environment ?? "development",
      });

      const uid = context.auth!.uid;

      await flamelinkApp.users.addToDB({
        uid: uid,
        data: {
          permissions: "user",
        },
      });
    }
  );
```

Any help?
Ryan

**Comment by gitdubz** [comment]
Hi @SKLn-Rad,

Could you kindly share the error message you are receiving? 

With regards to the isAdminApp, this has been deprecated so there is no need to pass it in on the latest versions of the SDK.

**Comment by SKLn-Rad** [comment]
Hey all, seems to be fine after deployment so wondering if it was an issue pointing to the emulator, closing now.
