### ISSUE TITLE
How to show title in content

### ISSUE THREAD

**Issue by bryan-sebastian** [flamelink/flamelink#15]
Hello, can I ask what field that I need to use to have my content a title in CMS.

**Comment by SpooN1337** [comment]
Hi @bryan-sebastian when creating a schema, you will notice when you add a field to your schema, and you select the field, at the bottom of the settings for that field, there should be a switch/toggle "Show in overview table", switch that on, and save. You should now see the field and its value in the table.

**Comment by bryan-sebastian** [comment]
Hello @SpooN1337, I saw the switch and now there is a title for my contents. Thank you!
