### ISSUE TITLE
Return existing firebase app instead of trying to re-initialize it.

### ISSUE THREAD

**Issue by wezz** [flamelink/flamelink#18]
I'm creating a site using Nuxt.js. 
Flamelink is initialized through a module used by my Vuex store. My helper function will check to see if there already is a Flamelink instance initiated and return that.

The problem is that even though I don't re-run the Flamelink initialize function, the global instance of Firebase is still active. That means that on my reloads Firebase will throw the error:

> Firebase: Firebase App named 'MYAPPNAME' already exists (app/duplicate-app).

I think Flamelink should check for a previously existing app before trying to initialize

I solved it locally by doing the following:
`if(firebase.apps && firebase.apps.length > 0)
{
	this.firebaseApp = firebase.apps[0];
}
else
{
	this.firebaseApp = firebase.initializeApp(this.firebaseConfig);
}
this.flamelinkApp = await flamelink({ firebaseApp: this.firebaseApp });
`

**Comment by dewetvdm** [comment]
Thanks for reporting @wezz, will add this to the SDK to check if there is a default instance or an instance with the name existing and use it if found.

**Comment by elcferreira** [comment]
I have the same problem.
I'm using the flamelink sdk to integrate with my ecommerce (vuejs/nuxt).
But did occur this error.

**Comment by wezz** [comment]
When can we expect the next SDK release?

**Comment by mime55** [comment]
@wezz : Can you please tell us where to insert your snippet. I need a temporary solution as well.

**Comment by wezz** [comment]
@mime55 @elcferreira 
Here is my file where I initiate flamelink & firebase.

https://pastebin.com/j1h5fmr1

**Comment by elcferreira** [comment]
Hello, in my case I use flamelink in nuxtjs, but here is the code to how to integrate flamelink at your application.

``javascript
import firebase from 'firebase'
import flamelink from 'flamelink'

let firebaseApp

if(firebase.apps && firebase.apps.length > 0) {
  firebaseApp = firebase.apps[0]
} else {
      firebaseApp = firebase.initializeApp({
        apiKey: "<apiKey>",
        authDomain: "<authDomain>",
        databaseURL: "<databaseURL>",
        projectId: "<projectId>",
        storageBucket: "<storageBucket>",
        messagingSenderId: "<messagingSenderId>"
      })
}

let flamelinkApp = Flamelink({ firebaseApp })
``

**Comment by jperasmus** [comment]
Here is an example of how you can use `flamelink` with Nuxt for `server`, `client` or `static` usage: https://github.com/flamelink/examples/tree/master/examples/nuxt-basic
