### ISSUE TITLE
I use orderByChild and equalTo  but return null

### ISSUE THREAD

**Issue by lagmanzaza** [flamelink/flamelink#2]
![screen shot 2560-12-03 at 23 40 51](https://user-images.githubusercontent.com/5283709/33527668-3f75b4fc-d887-11e7-9790-35eaf26e7b2f.png)
![screen shot 2560-12-03 at 23 42 10](https://user-images.githubusercontent.com/5283709/33527669-3faa68be-d887-11e7-82b5-ca06ccf6b815.png)

**Comment by jperasmus** [comment]
Hi @lagmanzaza, I replied to you on Slack. Will update this ticket once the issue is resolved for you.

**Comment by jperasmus** [comment]
Just to update the ticket for others that might experience a similar thing: the problem here was that `category` is a number in the database, but a string from the route params. To fix, parse to int.

```
let products = await app.content.get('productID', {
  orderByChild: 'category',
  equalTo: parseInt(params.category, 10)
})
```
