### ISSUE TITLE
Forgot my credentials... How to renew my credentials ? 

### ISSUE THREAD

**Issue by rakipinsight** [flamelink/flamelink#20]
Forgot my credentials... How to renew my credentials ? Login page keeps on logging in with no response

**Comment by SpooN1337** [comment]
Hi @rakipinsight

If you are referring to your login credential on app.flamelink.io, you can simply select "Forgot my password" and then reset your password.

If you are referring to your login credential for a specific project, you have a couple of options.

1. If you have access to your firebase project via firebase.google.com, you can go to "Develop" -> "Authentication" -> search for your username -> click on the inline menu and select "Reset Password"
Once you have completed this step, you can try logging into your project using the new password

2. If you do not have access to your firebase project via firebase.google.com, you can ask your Administrator to either reset your password using the steps above, or simply do it through the Flamelink app.

In some cases we have found that if you clear your browser cache, this normally resolves the issue  (by clearing your cache, you will need to know your password)

**Comment by rakipinsight** [comment]
I was referring to login credentials for a specific project. Thanks for the info.
