### ISSUE TITLE
Question - Can you add users to a relational field?

### ISSUE THREAD

**Issue by JeffWeim** [flamelink/flamelink#21]
I have a schema set up and I would like to know if it is possible to add a relational field that has its relational data pointing to the Users that are already in Firebase db?

**Comment by shaunnez** [comment]
Definitely keen on this as well, I noticed there was an email/password field option but figured it'd be better if I could link it to users :D Great work by the way! I think if you tie in users / localization that this would be one of the better headless CMS's out there. P.s. can you make it so we can create our own "languages" (i.e. wookie) -- then you can say it can be used for white-labelling as well :)

**Comment by shaunnez** [comment]
It's me again, any update? :)

**Comment by grandadmiralmcb** [comment]
Would love to see an update on this

**Comment by dewetvdm** [comment]
This will be rolled out on the 25th of Feb 2019 along with being able to select navigation entries form the "select (relational)" & "tree (relational)" fields. The SDK might only be updated a short while after.

**Comment by rubenheymans** [comment]
I can link to a menu, but I can't find how to link with a menu item. So I can link a page with a menu item. Is this possible somehow?
