### ISSUE TITLE
Name/Title/ID of Flamelink-Entries are not displayed

### ISSUE THREAD

**Issue by dschroe** [flamelink/flamelink#22]
Hey guys,

i created a simple test-schema with one text-field:
![schema](https://user-images.githubusercontent.com/9927627/41924058-52023266-7969-11e8-80e5-cd088d7e7911.PNG)

and added a simple entry:
![entry](https://user-images.githubusercontent.com/9927627/41924166-97e3a1b6-7969-11e8-85a1-a027b95fe8b4.PNG)

In the entries-overview of the schema there is no title/name/id displayed for this entry...let's assume we have multiple entries, there is no chance to find a specific entry, unless i click through all of them:
![entries-overview](https://user-images.githubusercontent.com/9927627/41924369-1ff007de-796a-11e8-9595-b205b1834cc9.PNG)

Is that behaviour intended? Thanks in advance!

**Comment by jperasmus** [comment]
Hi @dschroe,

Thanks for using Flamelink.

If you go to your schema setup page and click on the title field you would like to show in the overview table, you can toggle the “Show in overview table” setting on. That should do the trick.

**Comment by dschroe** [comment]
Thanks for the hint. Flamelink is a great project! Keep up the good work ;-)

**Comment by jperasmus** [comment]
Thanks 🙂
