### ISSUE TITLE
Creating text field for slug 

### ISSUE THREAD

**Issue by tonis2** [flamelink/flamelink#25]
Hei,
I am trying to use flamelink for blog posts and its working well, but i have a question,

how could i add a field that creates a slug from post title like there is in documentation example.

```app.content.getByField('blog-posts', 'slug', 'my-famous-blog-post')```

I am trying to do the same thing.

**Comment by tonis2** [comment]
Found it myself it can be used as Linked-text field in schema creation.

**Comment by jperasmus** [comment]
Hi @tonis2

I am glad you found it. We had a small bug with the Linked Text field that we wanted to fix today first before I came back to you.

With that said, you can use any field with this function and the “slug” is just an example.
