### ISSUE TITLE
Unable to install flamelink via npm

### ISSUE THREAD

**Issue by theCubix** [flamelink/flamelink#27]
Hello there

Whilst trying to add the flamelink sdk to my project using npm, I get the following errors:

---

node-pre-gyp ERR! Tried to download(403): https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.10.1/node-v64-darwin-x64-unknown.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for grpc@1.10.1 and node@10.6.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp ERR! Pre-built binaries not installable for grpc@1.10.1 and node@10.6.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp ERR! Hit error Connection closed while downloading tarball file 
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/surface/init.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/surface/init.o
rm: ./Release/.deps/Release/obj.target/grpc/deps/grpc/src/core/lib/surface/init.o.d.raw: No such file or directory
make: *** [Release/obj.target/grpc/deps/grpc/src/core/lib/surface/init.o] Error 1
gyp ERR!   CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/avl/avl.o
build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--library=static_library" "--module=/Users/Timon/Desktop/WebDev/vuejs/iceland-book/node_modules/flamelink/node_modules/grpc/src/node/extension_binary/node-v64-darwin-x64-unknown/grpc_node.node" "--module_name=grpc_node" "--module_path=/Users/Timon/Desktop/WebDev/vuejs/iceland-book/node_modules/flamelink/node_modules/grpc/src/node/extension_binary/node-v64-darwin-x64-unknown"
gyp ERR! cwd /Users/Timon/Desktop/WebDev/vuejs/iceland-book/node_modules/flamelink/node_modules/grpc
gyp ERR! node -v v10.6.0
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --library=static_library --module=/Users/Timon/Desktop/WebDev/vuejs/iceland-book/node_modules/flamelink/node_modules/grpc/src/node/extension_binary/node-v64-darwin-x64-unknown/grpc_node.node --module_name=grpc_node --module_path=/Users/Timon/Desktop/WebDev/vuejs/iceland-book/node_modules/flamelink/node_modules/grpc/src/node/extension_binary/node-v64-darwin-x64-unknown' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/Timon/Desktop/WebDev/vuejs/iceland-book/node_modules/flamelink/node_modules/grpc/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:961:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
node-pre-gyp ERR! System Darwin 17.7.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/Timon/Desktop/WebDev/vuejs/iceland-book/node_modules/flamelink/node_modules/grpc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
node-pre-gyp ERR! cwd /Users/Timon/Desktop/WebDev/vuejs/iceland-book/node_modules/flamelink/node_modules/grpc
node-pre-gyp ERR! node -v v10.6.0
node-pre-gyp ERR! node-pre-gyp -v v0.7.0
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --library=static_library --module=/Users/Timon/Desktop/WebDev/vuejs/iceland-book/node_modules/flamelink/node_modules/grpc/src/node/extension_binary/node-v64-darwin-x64-unknown/grpc_node.node --module_name=grpc_node --module_path=/Users/Timon/Desktop/WebDev/vuejs/iceland-book/node_modules/flamelink/node_modules/grpc/src/node/extension_binary/node-v64-darwin-x64-unknown' (1)
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/backoff/backoff.oe
../deps/grpc/src/core/lib/backoff/backoff.cc:23:10: fatal error: l: Failed to e
      'src/core/lib/gpr/useful.h' file not found
#include "src/core/lib/gpr/useful.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make: *** [Release/obj.target/grpc/deps/grpc/src/core/lib/backoff/backoff.o] Error 1
gyp ERR! build error ⠸ install: info lifecycle grpc@1.10.1~install: Failed to e
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--library=static_library" "--module=/Users/Timon/Desktop/WebDev/vuejs/iceland-book/node_modules/flamelink/node_modules/grpc/src/node/extension_binary/node-v64-darwin-x64-unknown/grpc_node.node" "--module_name=grpc_node" "--module_path=/Users/Timon/Desktop/WebDev/vuejs/iceland-book/node_modules/flamelink/node_modules/grpc/src/node/extension_binary/node-v64-darwin-x64-unknown"
gyp ERR! cwd /Users/Timon/Desktop/WebDev/vuejs/iceland-book/node_modules/flamelink/node_modules/grpc
gyp ERR! node -v v10.6.0
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! grpc@1.10.1 install: `node-pre-gyp install --fallback-to-build --library=static_library`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the grpc@1.10.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Timon/.npm/_logs/2018-07-29T18_33_42_563Z-debug.log
command failed: npm install --loglevel error flamelink

---

Any ideas how to fix this?

Many thanks

**Comment by theCubix** [comment]
Hi @jperasmus,

Sure thing, I had to use at least v8.9 for vue cli to work and flamelink now installed without any errors.

Many thanks for the help 👍

**Comment by lopugit** [comment]
How is this not an easy fix????? Make grpc a dependency of flamelink??????

**Comment by lopugit** [comment]
Why using prebuilts????

**Comment by jperasmus** [comment]
We have a [new SDK](https://github.com/flamelink/flamelink-js-sdk) currently in `alpha` that supports Node.js v10.

Does this SDK work in Node.js v10 when you add `grpc` as a dependency of your app?

**Comment by pimdewit** [comment]
> We have a [new SDK](https://github.com/flamelink/flamelink-js-sdk) currently in `alpha` that supports Node.js v10.
> 
> Does this SDK work in Node.js v10 when you add `grpc` as a dependency of your app?

It does not.

Is there any update on this? Gettiung the same issue on newer node versions (tried 10, 11.13, 12.3.1)

**Comment by jperasmus** [comment]
@pimdewit Is there a possibility for you to use the new SDK?
