### ISSUE TITLE
View Form dialog doesn't show information

### ISSUE THREAD

**Issue by Herohtar** [flamelink/flamelink#29]
When clicking on the "View" button for a form entry, it just brings up a dialog that lists all the names of the form fields, but the content of the fields is not shown.

**Comment by jperasmus** [comment]
Hi @Herohtar, apologies for the delay. Are you still experiencing this issue? I've checked now quick and the View that I tested showed the fields with their values.

**Comment by Herohtar** [comment]
It looks like the issue has been fixed! Thanks!
