### ISSUE TITLE
Firestore

### ISSUE THREAD

**Issue by Adam-Burke** [flamelink/flamelink#3]
Hi There,

Cool product!
Is a goal of yours to support firestore?

**Comment by jperasmus** [comment]
Hi @Adam-Burke 

Sorry for the radio silence, most of us took a bit of a break over the holidays. We have started the conversation around support for Firestore but have not come to any concrete decision just yet, unfortunately. I can foresee a future where we would potentially allow the developer to specify which DB s/he wants to use (firestore or real-time db).

**Comment by willoughby** [comment]
I think the addition of Firestore would be awesome, the fact you can do more complicated selects is a nice win.

**Comment by jperasmus** [comment]
For sure, querying Firestore looks very promising! Ran into a lot of limitations trying to do complex queries against the Firebase real-time db with our JavaScript SDK.

**Comment by willoughby** [comment]
Yeah I can imagine, I used real time db on a few projects but had to migrate them to mongo as the queries became complicated. My latest project though I've used Firestore throughout and its the project we use Flamelink on.

**Comment by jperasmus** [comment]
I'll make sure that we keep this on the roadmap for things to look at rolling out even though I do not think that it will be within the next few months. The focus at the moment is to try and make the current functionality as solid as possible.

I'm going to close this issue off for now. Thanks for the discussion.

**Comment by ducpt2** [comment]
@jperasmus  Hi, any update on firestore?

Thanks :)

**Comment by jperasmus** [comment]
Hi @ducpt2 yes, we'll be rolling out support for Firestore soon.
