### ISSUE TITLE
Installation crashes on node version 10 (10.8.0)

### ISSUE THREAD

**Issue by christiansany** [flamelink/flamelink#30]
When you want to install the package under node 10.8.0 it just completely crashes.

**Comment by jperasmus** [comment]
This will be resolved as part of the SDK v1 release. Track it here: https://github.com/flamelink/flamelink/issues/49

**Comment by jperasmus** [comment]
An alpha version of the new SDK that is compatible with Node.js v10 is available: https://flamelink.github.io/flamelink-js-sdk/#/migration-guide

**Comment by f-gueguen** [comment]
Would you have an estimated release date for a v1?
Google Cloud will ask for nodejs10 on new  instances from 1st of October
![image](https://user-images.githubusercontent.com/20118221/64679231-4b103300-d4b6-11e9-8180-f589dd1ab1c0.png)
[Google cloud doc](https://cloud.google.com/appengine/docs/standard/nodejs/runtime?hl=en_US&_ga=2.144247603.-748275084.1565317385&_gac=1.180490069.1566455610.CjwKCAjw1_PqBRBIEiwA71rmtZHPPvtCkN4Rl5dJZygC8v2qyoF_BQN8vP9HXl_zoMdoQJz6uzpcjxoCKkMQAvD_BwE)

Thank you!
