### ISSUE TITLE
Nested Repeater is Required

### ISSUE THREAD

**Issue by Alimudassar111** [flamelink/flamelink#33]
I have an issue with repeater functionality...
My situation is something like while creating a schema
I have a Parent Mall that may have multiple shops so I'm using repeater within that parent mall
and each shop in the repeater could have many comments so I also need a nested repeater.

**Comment by dewetvdm** [comment]
Hi @Alimudassar111, currently we do not allow for nested repeaters, but there is a work around

I can suggest splitting the two, and linking them with a relational select field
 
Schema: Malls (Single or Collection)
 -> repeater
   -> Mall Name: text input
   -> Shops: relational select - with relational data = Shops and multi select true

Schema: Shops (Collection)
 -> Shop Name: text
 -> Comments: repeater
       -> Comment: text input / textarea / wysiwyg

Then you can use the populate method provided on the SDK

**Comment by Alimudassar111** [comment]
Thank you so much for the solution . Happy coding 😉😎

**Comment by Alimudassar111** [comment]
i need help about the populate method....

**Comment by Alimudassar111** [comment]
![screen shot 2018-08-25 at 3 52 31 am](https://user-images.githubusercontent.com/6438416/44611424-7c21b500-a81a-11e8-8386-7090adc246e9.png)
![screen shot 2018-08-25 at 3 52 42 am](https://user-images.githubusercontent.com/6438416/44611427-80e66900-a81a-11e8-81a5-a448565e647d.png)

**Comment by Alimudassar111** [comment]
these are the two images ...
I have mall schema and shopSchema
so how I can populate or whatever. 
I just need all the info about the shops that are attached to that specific mall
