### ISSUE TITLE
flamelink + React Native = Error

### ISSUE THREAD

**Issue by Alimudassar111** [flamelink/flamelink#34]
![img_0423](https://user-images.githubusercontent.com/6438416/44612681-b479c100-a823-11e8-9695-5f92c1541c50.PNG)
I was trying to use React Native and flame link but I got this error can you please guide me?

**Comment by dewetvdm** [comment]
Hi @Alimudassar111 , try installing `babel-preset-env` 

`npm install --save-dev babel-preset-env` or 
`yarn add babel-preset-env --dev`

Then in your **.babelrc** add `babel-preset-env` to your presets array
```
{ 
  "presets": ["babel-preset-env"],
   ...
   ...
}
```

**Comment by Alimudassar111** [comment]
Thanks
