### ISSUE TITLE
Minor Issue with Default Date Format

### ISSUE THREAD

**Issue by jessefrye** [flamelink/flamelink#35]
- Default date format is set to `dd/mm/yyyy` in global settings.
    - Changing through the GUI wouldn't save but changing through the firebase db worked fine.
- If you change the default date format as above the "default value" will remain `dd/mm/yyyy` within the schema details (on the left) but on the right where the schema fields are the date format is correct.  Also, when creating a new post the default value is correct despite the default view in the schema. 

I will take a look later but wanted to document.

![image](https://user-images.githubusercontent.com/127787/44639773-83f46d00-a972-11e8-9c37-e64e7666029f.png)

**Comment by jperasmus** [comment]
Hi @jessefrye thanks for taking the time to report this. I'll take a look 👍

**Comment by jperasmus** [comment]
Hi, we've made some fixes around the display format for both the "Date" and "Datetime Local" fields which should be going into our next release within this or next week. I'll post another comment here when we've done the release.

Thanks again for reporting this.

**Comment by jperasmus** [comment]
These fixes were released last week 👻

**Comment by jessefrye** [comment]
👏 👏 👏  thanks @jperasmus I'll check it out
