### ISSUE TITLE
How do i query and use it in android app?

### ISSUE THREAD

**Issue by princiee** [flamelink/flamelink#36]

**Comment by jperasmus** [comment]
Hi @princiee thanks for your question. We are looking into an official Android SDK for Flamelink, but in the mean time you can use the Firebase SDK for Android to retrieve your data from the realtime DB and storage bucket: https://firebase.google.com/docs/database/android/read-and-write

**Comment by superdiazzz** [comment]
@jperasmus So we can retrieve data manually with firestore way?
