### ISSUE TITLE
Can I use webhooks?

### ISSUE THREAD

**Issue by Herohtar** [flamelink/flamelink#38]
Does Flamelink have any support for webhooks so it can trigger a static site generator build when content in the CMS changes? If not, consider this a feature request. ;)

**Comment by jperasmus** [comment]
Hi @Herohtar thanks for taking the time to log this issue. We have started with work on Webhooks from within the CMS to make exactly what you are saying easier to our users, but we've decided to prioritize some other features first. The reason for this is that, yes, we definitely want to implement webhooks and it will add a lot of value, but at this stage, it is possible for users to set up Firebase Cloud Functions to trigger their static site generator builds and other webhook endpoints using cloud functions.

**Comment by Herohtar** [comment]
I wondered if Cloud Functions might be the only way to do it at the moment. The only downside to that is it doesn't work for projects that are on the Spark (free) plan, as access to things outside of Google is blocked. I'm glad to hear support for webhooks within the CMS is in the works, as managing a Cloud Function isn't the most convenient method.

**Comment by jperasmus** [comment]
I forgot about this issue. Just wanted to let you know that Webhooks is a feature that we released recently if you wanted to still check it out.
