### ISSUE TITLE
Save unsuccessful - no data supplied on save

### ISSUE THREAD

**Issue by oldtimerza** [flamelink/flamelink#39]
Ive uploaded some of my content through the API ,now when I make manual edits to that data through the CMS GUI , I get a "Save unsuccessful - no data supplied on save" error . Am I doing something wrong, did I miss a setting or is this a bug? 
Thanks for the help.

**Comment by jperasmus** [comment]
Hi @oldtimerza thanks for reaching out.

Can you please provide me with an example of the content that you added via the SDK and how it shows up for you in the CMS?
