### ISSUE TITLE
User authentication failed Invalid CMS user

### ISSUE THREAD

**Issue by kimbummen** [flamelink/flamelink#40]
i can not log in to my flamelink project ? 
When i login by my email and password, the error message "User authentication failed
Invalid CMS user" always show. Can anyone help me to solve it ?

**Comment by dewetvdm** [comment]
Hi @kimbummen, I am able to help. You can try the following:

# Option 1
1. Please remove the project on Flamelink - Don't worry, you won’t loose any work or data
https://cl.ly/e3dc014f97ba

2. Then delete the users you are not able to login with from the users node in your database
`flamelink` > `users` > delete user(s) that can not login

3. Add the project again

4. Once the project is added - go to `Manage Project` -> `CMS Users` and add the user(s) again.
https://cl.ly/8c09d0c210a1
https://cl.ly/5078db1e349d

# Option 2

1. Export your firebase database to JSON
2. Go to your Firebase `Authentication` section and copy the UID of the user that you are unable to login with
3. Update the `key` and  `id` field of the user you are unable to login with
example

`"current-broken-UID": {
 ...,
 "firstname":  ...,
 "id": "current-broken-UID"
}`

to 

`"copied-UID:" {
 ...,
 "firstname":  ...,
 "id": "copied-UID"
}`

4. upload your saved JSON file and try to login again
