### ISSUE TITLE
Angular Universal Problem

### ISSUE THREAD

**Issue by quanganh206** [flamelink/flamelink#43]
Angular Universal + NgRx Effect + Flamelink halt.

I try to retest with other ways all work. HttpClient call, Service call direct from Firebase Flamelink data, all work. But that snippet not working.

        // const getContentObservable: any = bindCallback(this.dataService.getApp().content.subscribe);
        // return getContentObservable('articles', { populate: ['image', 'tags'] })
        //     .pipe(
        //         map((results: any) => results.filter(item => item != null)),
        //         map((item: any) => {
        //             const items = [];
        //             for (const value of Object.values(item[0])) {
        //                 items.push(value);
        //             }
        //             return items;
        //         }),
        //         tap((res) => this.state.set(POST_KEY, res as any))
        //     );

**Comment by jperasmus** [comment]
Hi @quanganh206 

Can you please explain what you are expecting to see and what you are getting? Is this piece of code from the basic Angular example?

**Comment by quanganh206** [comment]
No, your basic Angular example work I tested with it yet. That code snippet should work too with ng serve. 

But when you try to build and run with SSR it did not work. It doesn't through any errors but loading time never end. That code just turn your api call to observable stream to working with Ngrx effect.

**Comment by quanganh206** [comment]
Or you just try to call a simple api call like your example in a Basic Angular Universal like in https://angularfirebase.com/snippets/angular-6-universal-simple-guide

You will see the infinity loading with just simple method like that:

ngOnInit() {
     this._fl.getApp().content.subscribe('articles', { populate: ['image', 'tags']}, (error, data) => {
      if (error) {
        console.error(error);
      }
      console.log(data);
    });
  }

**Comment by jperasmus** [comment]
If this is the same problem I've seen previously, the problem is with Angular not being able to determine when content has been received over the Firebase websocket, so it keeps waiting until it times out at around a minute.

https://github.com/angular/angular-cli/issues/9985#issuecomment-378833570

**Comment by quanganh206** [comment]
Great, thank @jperasmus I will try and feedback soon.

**Comment by jkinger** [comment]
@quanganh206 Did you ever get this working?  I'm now struggling with the same problem too.. I've been battling this problem for the last 3 days with not much luck.  Flamelink will work via `ng serve` just fine but as soon as you try serving a built Universal package, the page spins and eventually times out.  I'll remove Flamelink sdk reference and Universal will load just fine.  Been basing part of my implementation off of [angular-basic example](https://github.com/flamelink/examples/tree/master/examples/angular-basic)

I feel like I've searched high and low tryin all kinds of techniques and possible solutions.  Various combinations of node v8, 10, 11. Angular 6, 7. AngularFire 4, 5.  Even @jperasmus solution and again, everything will run just fine without Flamelink but as soon as I add it, it hangs.  

I did stumble across [one lone git repo](https://github.com/jamesdaniels/AngularFireDocs) that I got Flamelink to work with their Universal implementation but haven't been able to successfully mimic what they did in a fresh project just yet but I'll continue to dissect it...

**Comment by quanganh206** [comment]
@jkinger, no I have no luck too. Look like Flamelink not return data when it get data, merge and populate from firebase.

**Comment by jkinger** [comment]
@quanganh206, 

Through some trial and error, I was able to get this working….  Oddly enough, I had to include AngularFireDatabase module from the AngularFire package in the service I instantiated the Flamelink SDK in along with adding it as a dependency.  For example, see mine at [flamelink.service.ts]( https://github.com/jkinger/Angular-Universal-Flamelink/blob/master/src/app/flamelink.service.ts) to see what I mean.

That’s what it took to get it working for me, very simple but took too long to narrow it down to that.  I found this worked for Angular 6+ and AngularFire 4+ BUT only for Node v8 (issue #27).  

Since this was such a process I created a full working project using [Angular Universal + Flamelink](https://github.com/jkinger/Angular-Universal-Flamelink) hosted with Firebase Hosting / Functions that can be used as a template.  Feel free to use it to see if you can get yours working...

Good luck!

**Comment by ohabash** [comment]
```
getData(data: string, next) {
    console.log('start get data'); // i do see this on server console
    this.flame.content.content.get(data).then(response => {
        console.log(response); // never see on server console (only angular app without ssr)
        return next(response);
    }).catch(error => {
        //this error does not log with ssr
        console.error(error);
    });
}
```

Before the `catch` or the `then` runs I get the following error on the server log (but not when do the same thing in Angular minus ssr

>ERROR HttpErrorResponse {
  headers: HttpHeaders { normalizedNames: Map {}, lazyUpdate: null, headers: Map {} },
  status: 0,
  statusText: 'Unknown Error',
  url: null,
  ok: false,
  name: 'HttpErrorResponse',
  message: 'Http failure response for (unknown url): 0 Unknown Error',
  error: 
   ProgressEvent {
     type: 'error',
     target: 
      XMLHttpRequest {
        onloadstart: null,
        onprogress: null,
        onabort: null,
        onerror: null,
        onload: null,
        ontimeout: null,
        onloadend: null,
        _listeners: [Object],
        onreadystatechange: null,
        _anonymous: undefined,
        readyState: 4,
        response: null,
        responseText: '',
        responseType: 'text',
        responseURL: '',
        status: 0,
        statusText: '',
        timeout: 0,
        upload: [XMLHttpRequestUpload],
        _method: 'GET',
        _url: [Url],
        _sync: false,
        _headers: [Object],
        _loweredHeaders: [Object],
        _mimeOverride: null,
        _request: null,
        _response: null,
        _responseParts: null,
        _responseHeaders: null,
        _aborting: null,
        _error: null,
        _loadedBytes: 0,
        _totalBytes: 0,
        _lengthComputable: false },
     currentTarget: 
      XMLHttpRequest {
        onloadstart: null,
        onprogress: null,
        onabort: null,
        onerror: null,
        onload: null,
        ontimeout: null,
        onloadend: null,
        _listeners: [Object],
        onreadystatechange: null,
        _anonymous: undefined,
        readyState: 4,
        response: null,
        responseText: '',
        responseType: 'text',
        responseURL: '',
        status: 0,
        statusText: '',
        timeout: 0,
        upload: [XMLHttpRequestUpload],
        _method: 'GET',
        _url: [Url],
        _sync: false,
        _headers: [Object],
        _loweredHeaders: [Object],
        _mimeOverride: null,
        _request: null,
        _response: null,
        _responseParts: null,
        _responseHeaders: null,
        _aborting: null,
        _error: null,
        _loadedBytes: 0,
        _totalBytes: 0,
        _lengthComputable: false },
     lengthComputable: false,
     loaded: 0,
     total: 0 } }
[ { __meta__: 
     { createdBy: '3x54UStvuhQN08AAdESpIi5iXsQ2',
       createdDate: '2019-02-08T20:28:11.126Z',
       lastModifiedBy: '3x54UStvuhQN08AAdESpIi5iXsQ2',
       lastModifiedDate: '2019-02-11T17:03:54.921Z' },
    desc: 'On all orders shipping to the continental US',
    heading: 'Free Shipping',
    icon: 'fas fa-truck',
    id: 1549657691126 },
  { __meta__: 
     { createdBy: '3x54UStvuhQN08AAdESpIi5iXsQ2',
       createdDate: '2019-02-08T20:42:52.582Z',
       lastModifiedBy: '3x54UStvuhQN08AAdESpIi5iXsQ2',
       lastModifiedDate: '2019-02-11T17:01:12.110Z' },
    desc: 'Pre or post order - we are here to help answer questions',
    heading: 'Free Technical Support',
    icon: 'fas fa-life-ring',
    id: 1549658572582 },
  { __meta__: 
     { createdBy: '3x54UStvuhQN08AAdESpIi5iXsQ2',
       createdDate: '2019-02-08T20:43:32.309Z',
       lastModifiedBy: '3x54UStvuhQN08AAdESpIi5iXsQ2',
       lastModifiedDate: '2019-02-11T17:02:39.103Z' },
    desc: 'Hardware integration, firmware updates & burnin',
    heading: 'Free Assembly',
    icon: 'fas fa-cogs',
    id: 1549658612309 },
  { __meta__: 
     { createdBy: '3x54UStvuhQN08AAdESpIi5iXsQ2',
       createdDate: '2019-02-08T20:43:58.227Z',
       lastModifiedBy: '3x54UStvuhQN08AAdESpIi5iXsQ2',
       lastModifiedDate: '2019-02-11T17:03:30.591Z' },
    desc: 'Consult an expert to ensure you get the right product the first time',
    heading: 'Free Solution Architecting',
    icon: 'fas fa-sitemap',
    id: 1549658638227 } ]

**Comment by ohabash** [comment]
My node version is `v9.2.0`

**Comment by jkinger** [comment]
Have you tried using node v8.x? That was the only version I was able to get this to work with.. see issue #27 .

**Comment by ohabash** [comment]
@jkinger Maybe a dumb question but what steps are envolved in changing the node version...

I can easily run `nvm use v8.0.0` but then when i build i get all kinds of errors like

>ERROR in Module build failed: Error: Missing binding /Users/ohabash/Dropbox (Personal)/Sites/fornida-ng6/node_modules/node-sass/vendor/darwin-x64-57/binding.node
Node Sass could not find a binding for your current environment: OS X 64-bit with Node.js 8.x
Found bindings for the following environments:
  - OS X 64-bit with Node.js 9.x
This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass --force` to build the binding for your current environment.

**Comment by jperasmus** [comment]
@ohabash Have you tried running `npm rebuild node-sass --force` to create a new binding for v8?

I'm not sure yet whether you have the same problem that the others experienced, but their problem boils down to this: Angular Universal has a mechanism to determine when all the needed data is loaded server-side before it sends the response back to the browser, but it struggles to detect the data across Firebase's special real-time DB WebSocket implementation. In short, it keeps waiting for the WebSocket, long after the data has been received, and then times out around a minute later.

Looking at your example, this part does look strange with the double `content.content`: `this.flame.content.content.get(data)` - are you sure that is correct?

**Comment by jperasmus** [comment]
For the WebSocket timeout issue, an idea I had was to use the RTDB's `goOffline()` method on the server to manually close the connection - which I'm hoping will then allow Angular to determine it found all the content it needs to respond.

Something like this (again, I'm not very clued up around Angular, but have looked into this before):
```
async getData(schemaKey: string, next) {
    const content = await this.flamelinkApp.content.get(schemaKey)

    if (!isPlatformBrowser(this.platformId)) { // Or some other way to determine server code
      this.flamelinkApp.dbService.goOffline()
    }

    return next(content);
}
```

Not handling errors in the example to keep the code example as simple as possible

**Comment by ohabash** [comment]
You are right. Maybe I am not seeing the same problem as other ppl. Render does actually complete and the page does load at a normal speed. The error on the console is as follows and scripts do load afterwards. 

I guess there are 2 things that define my problem. (1) `HttpErrorResponse` in console. (2) when i view page source i do not see flameLink data. 

How can i get the flameLink data in the page source?

```ERROR HttpErrorResponse {
  headers: HttpHeaders { normalizedNames: Map {}, lazyUpdate: null, headers: Map {} },
  status: 0,
  statusText: 'Unknown Error',
  url: null,
  ok: false,
  name: 'HttpErrorResponse',
  message: 'Http failure response for (unknown url): 0 Unknown Error',
  error: 
   ProgressEvent {
     type: 'error',
     target: 
      XMLHttpRequest {
        onloadstart: null,
        onprogress: null,
        onabort: null,
        onerror: null,
        onload: null,
        ontimeout: null,
        onloadend: null,
        _listeners: [Object],
        onreadystatechange: null,
        _anonymous: undefined,
        readyState: 4,
        response: null,
        responseText: '',
        responseType: 'text',
        responseURL: '',
        status: 0,
        statusText: '',
        timeout: 0,
        upload: [Object],
        _method: 'GET',
        _url: [Object],
        _sync: false,
        _headers: [Object],
        _loweredHeaders: [Object],
        _mimeOverride: null,
        _request: null,
        _response: null,
        _responseParts: null,
        _responseHeaders: null,
        _aborting: null,
        _error: null,
        _loadedBytes: 0,
        _totalBytes: 0,
        _lengthComputable: false },
     currentTarget: 
      XMLHttpRequest {
        onloadstart: null,
        onprogress: null,
        onabort: null,
        onerror: null,
        onload: null,
        ontimeout: null,
        onloadend: null,
        _listeners: [Object],
        onreadystatechange: null,
        _anonymous: undefined,
        readyState: 4,
        response: null,
        responseText: '',
        responseType: 'text',
        responseURL: '',
        status: 0,
        statusText: '',
        timeout: 0,
        upload: [Object],
        _method: 'GET',
        _url: [Object],
        _sync: false,
        _headers: [Object],
        _loweredHeaders: [Object],
        _mimeOverride: null,
        _request: null,
        _response: null,
        _responseParts: null,
        _responseHeaders: null,
        _aborting: null,
        _error: null,
        _loadedBytes: 0,
        _totalBytes: 0,
        _lengthComputable: false },
     lengthComputable: false,
     loaded: 0,
     total: 0 } }
[ { __meta__: 
     { createdBy: '3x54UStvuhQN08AAdESpIi5iXsQ2',
       createdDate: '2019-02-08T20:28:11.126Z',
       lastModifiedBy: '3x54UStvuhQN08AAdESpIi5iXsQ2',
       lastModifiedDate: '2019-02-11T17:03:54.921Z' },
    desc: 'On all orders shipping to the continental US',
    heading: 'Free Shipping',
    icon: 'fas fa-truck',
    id: 1549657691126 },
  { __meta__: 
     { createdBy: '3x54UStvuhQN08AAdESpIi5iXsQ2',
       createdDate: '2019-02-08T20:42:52.582Z',
       lastModifiedBy: '3x54UStvuhQN08AAdESpIi5iXsQ2',
       lastModifiedDate: '2019-02-11T17:01:12.110Z' },
    desc: 'Pre or post order - we are here to help answer questions',
    heading: 'Free Technical Support',
    icon: 'fas fa-life-ring',
    id: 1549658572582 },
  { __meta__: 
     { createdBy: '3x54UStvuhQN08AAdESpIi5iXsQ2',
       createdDate: '2019-02-08T20:43:32.309Z',
       lastModifiedBy: '3x54UStvuhQN08AAdESpIi5iXsQ2',
       lastModifiedDate: '2019-02-11T17:02:39.103Z' },
    desc: 'Hardware integration, firmware updates & burnin',
    heading: 'Free Assembly',
    icon: 'fas fa-cogs',
    id: 1549658612309 },
  { __meta__: 
     { createdBy: '3x54UStvuhQN08AAdESpIi5iXsQ2',
       createdDate: '2019-02-08T20:43:58.227Z',
       lastModifiedBy: '3x54UStvuhQN08AAdESpIi5iXsQ2',
       lastModifiedDate: '2019-02-11T17:03:30.591Z' },
    desc: 'Consult an expert to ensure you get the right product the first time',
    heading: 'Free Solution Architecting',
    icon: 'fas fa-sitemap',
    id: 1549658638227 } ]```

**Comment by ohabash** [comment]
i cant find the `goOffline()` in the flamelink app or the documentation. I see `flamelink.content.unsubscribe` thought

**Comment by ohabash** [comment]
I think i do have the same hangup error. I can see in the logs the the request was made but nothing returned. No error nothing happens afterwards. The browser just waits.

im using node `v8.9.4` 

I am working on `goOffline()` but no luck so far (same results).

>also the content.content was a typo in this thread but my code is fine.

**Comment by ohabash** [comment]
I noticed occasionally ssr works after an uncomfortable wait with the following set up. But still hangs most of the time. 

Even once it loaded all content quickly. Weird. 

```
import { Injectable, Inject } from '@angular/core';
import * as flamelink from 'flamelink';
import { FirebaseApp } from '@angular/fire';
import { LocalstorageService } from "./localstorage.service";
import { AngularFireDatabase } from '@angular/fire/database';

@Injectable({
  providedIn: 'root'
})
export class FlamelinkService {

	flame: any; content: any; storage: any;
    
    private _flApp: flamelink.App;
    
	get flApp(): flamelink.App { return this._flApp; }
	set flApp(value: flamelink.App) { this._flApp = value; }

	constructor(
		@Inject(FirebaseApp) private _fb: firebase.app.App,
		private localstorageService: LocalstorageService,
		private db: AngularFireDatabase
	) {
		// if(localstorageService.isBrowser) {
			this.flame = flamelink({
				firebaseApp: this._fb,
				env: 'production',
				locale: 'en-US'
			});
			this.content = this.flame.content;
			this.storage = this.flame.storage;
		// }
	}

	async getData(schemaKey: string) {
        const content = await this.content.get(schemaKey);
        return content;
	}
}
```

**Comment by jperasmus** [comment]
@ohabash As you mentioned and you can see in the error logs, your content does actually show up, which means Flamelink/Firebase already successfully fetched the content.

The problem comes in with Angular's mechanism not being able to detect that it already received all the necessary info and can respond back to the browser. According to my understanding, Angular uses a thing called "zones" that helps monitoring the runtime of your app. On the server, it waits to go into a "stable" state before it responds back to the browser. Any detected asynchronous code (Promises, Observables, WebSockets, etc) still running will cause it not to go into this "stable" state. In this case, I believe it is because of the specific WebSocket connection used by Firebase's Real-time database. In this version of the SDK, the WebSocket connection is automatically created when the Flamelink app instance is created, but in the upcoming v1 release, it will be lazy-created, ie. only opened the first time you try and access something from the Firebase service.

This gives me an idea. Along with the `this.flame.databaseService.goOffline()` to force close the realtime DB connection, can you also force close the Firestore service connection (just in case) with: `this.flame.firestoreService.disableNetwork()`

----

If that doesn't work, here are a couple more things to try:

Looking at the example in your repo...

<img width="464" alt="get-data" src="https://user-images.githubusercontent.com/6787452/53303736-b0803780-3876-11e9-86a6-58169ef34cc5.png">

I would recommend that you return the Promise in the function. What I'm thinking: Angular needs to somehow keep track of any asynchronous data fetching taking place to determine when it is safe to respond back to the browser and maybe it has no idea when these promises resolve/reject. There might be a few of these examples in your repo to also double check.

What I would suggest is to create a simplified example of just one data fetch to your Firebase DB (via the Flamelink SDK) and try and return the promise for it. Then also after the promise resolves, call the `goOffline()` method on the Firebase `databaseService` so that it can force the WebSocket connection closed.

----

If that doesn't work, this thread explains the problem very well with a bunch of ideas how to get around it: https://github.com/angular/universal/issues/846
