### ISSUE TITLE
Download url for sized images

### ISSUE THREAD

**Issue by theCubix** [flamelink/flamelink#44]
When querying for a populated image field, flamelink gives back an array with the different sized images. However, these don't have a download url. Is there an easy way to get this directly in the response?

I tried to create to manually create the download url, but apparently it's missing a token so firebase won't return me any image at all.

<pre>
    "sizes": [
        {
          "height": 9999,
          "path": "375_9999_100",
          "quality": 1,
          "width": 375
        },
        {
          "height": 9999,
          "path": "667_9999_100",
          "quality": 1,
          "width": 667
        },
        {
          "height": 9999,
          "path": "900_9999_100",
          "quality": 1,
          "width": 900
        },
        {
          "height": 9999,
          "path": "1080_9999_100",
          "quality": 1,
          "width": 1080
        },
        {
          "height": 9999,
          "path": "1440_9999_100",
          "quality": 1,
          "width": 1440
        },
        {
          "height": 9999,
          "path": "1920_9999_100",
          "quality": 1,
          "width": 1920
        }
      ],
</pre>

**Comment by jperasmus** [comment]
Hi @theCubix thanks for reaching out.

Can you please send me the code you are currently trying?

You can also use our JavaScript SDK's `app.storage.getURL()` method individually for each size that you want.

```
const sizes = [
  {
    "height": 9999,
    "path": "375_9999_100",
    "quality": 1,
    "width": 375
  },
  // etc...
]

Promise.all(sizes.map(size => app.storage.getURL('<your-file-id-here>', { size })))
  .then(images => {
    // do something with your images here
  })
  .catch(console.error)
```

**Comment by grantyi** [comment]
@jperasmus Does the method you're describing perform an additional API call to resolve the url for the size?

**Comment by jperasmus** [comment]
@grantyi yes, under the hood, this method uses the official Firebase **getDownloadUrl** method that asynchronously retrieves a long-lived download URL with a revokable token.

**Comment by theCubix** [comment]
@jperasmus Thanks for the fast respond

I first solved it using the firebase getDownloadURL method and changed it now to the flamelink method.

Works perfectly fine 👍🏼

**Comment by jperasmus** [comment]
Glad it worked for you
