### ISSUE TITLE
flamelink@0.19.6: The engine "node" is incompatible with this module. Expected version ">=6 <10".

### ISSUE THREAD

**Issue by naody** [flamelink/flamelink#46]
I'm getting the following errors while installing via `yarn add flamelink`, I know the error message is clear but is there any way I can use it with my current node version which is `v10.11.0`? If not what do I need to do, setting `engines` in `package.json` didn't help

 I tried. 
```
 "engines": {
    "node": "8"
  }
```

```
error flamelink@0.19.6: The engine "node" is incompatible with this module. Expected version ">=6 <10".
error Found incompatible module
```

**Comment by jperasmus** [comment]
Hi @naody 

Thanks for reaching out. Is it possible for you to downgrade your current Node version to be less than v10? We are looking into a significant refactor of this SDK in which we'll also ensure that it works with the latest version of Node, but that is still going to be a while before we can release it.

**Comment by naody** [comment]
Thanks, @jperasmus, I'll experiment with `node 8`.

**Comment by jperasmus** [comment]
Great, shout if you have any other questions

**Comment by mayurdhurpate** [comment]
#49

**Comment by mayurdhurpate** [comment]
#49
