### ISSUE TITLE
Pass new data to Firelink via SDK

### ISSUE THREAD

**Issue by dcp3450** [flamelink/flamelink#47]
I've checked the API docs and see a `set` option but that says I need to pass in a current content ID for updating. However, I'd like to use a form to pass data to firelink. Is this possible?

**Comment by dewetvdm** [comment]
You can simply create a new entry id before using the set method

example 

`
const newContentId = Date.now();

app.content.set('blog-posts', newContentId, { title: 'new-title' })
  .then(() => console.log('Setting the entry succeeded'))
  .catch(() => console.error('Something went wrong while setting the entry.'));
`
