### ISSUE TITLE
Firestore support for SDK

### ISSUE THREAD

**Issue by jperasmus** [flamelink/flamelink#49]
This JavaScript SDK does currently only support the Firebase Real-time Database.

This issue is a placeholder for all discussions around Firestore specifically.

We are in the process of developing version 1 of the SDK which will include support for Firestore.

Current workaround: https://github.com/flamelink/flamelink/issues/45#issuecomment-438566190

**Comment by jperasmus** [comment]
We're aiming to release in Q1 of this year (2019).

**Comment by jperasmus** [comment]
Hi all, an `alpha` version of the new JavaScript SDK that supports both the Real-time DB as well as Cloud Firestore is available.

You can install the alpha version using the `next` tag: `npm install flamelink@next`.
New documentation: https://flamelink.github.io/flamelink-js-sdk
Migration guide: https://flamelink.github.io/flamelink-js-sdk/#/migration-guide
New repo: https://github.com/flamelink/flamelink-js-sdk

Please do take note that this is an **alpha** version, so there might be breaking changes from now until it is released to General Availability.

If you find any issues, please log them in the new repo.

**Comment by shaunnez** [comment]
hi @jperasmus  that's awesome thanks. Regarding the flamelink CMS itself...
Is the idea the the "Administration -> Users" tab will show all users who register to your firebase application? The note at the top of the tab suggests so... my assumption that it's only linked to the realtime db at the moment?

The message says "You can now manage your CMS users from the Manage Project > CMS Users section for your project. Users displayed here are all of your project users (CMS and non-CMS)"

However when I create a user "i.e. auth.createUserWithEmailAndPassword" they don't appear in this list. Thanks
