### ISSUE TITLE
Trying to integrate Flamelink in Cordova (Ionic 3)

### ISSUE THREAD

**Issue by DovahBrownies** [flamelink/flamelink#5]
Hey there!
Really loving the simplicity of the CMS you've brought to the table and I can't wait to get started with it.
Unfortunately, I am having a problem getting it to run with Ionic 3 running on Cordova.

Here's some code:

**app.module.ts**
```js
import { AngularFireDatabaseModule } from 'angularfire2/database';
import { AngularFireAuthModule, AngularFireAuth } from 'angularfire2/auth';
import { AngularFireModule, FirebaseAppProvider } from 'angularfire2';
import * as firebase from "firebase";
import { AngularFireDatabase, FirebaseListObservable } from "angularfire2/database-deprecated";

import flamelink from 'flamelink';

export const firebaseConfig = {
    apiKey: "XXXXX",
    authDomain: "XXXX.firebaseapp.com",
    databaseURL: "https://XXXX.firebaseio.com",
    storageBucket: "XXXX.appspot.com",
    projectId: "XXXX",
    messagingSenderId: "XXXX"
  };

// For flamelink -- https://flamelink.github.io/flamelink/#/getting-started
    const firebaseApp = AngularFireModule.initializeApp(firebaseConfig);
    const flamelinkApp = flamelink({ firebaseApp });

@NgModule({
    declarations: [
      //  ...
    ],
    providers: [
     //  ...
    FirebaseProvider,
    flamelink,
    AngularFireDatabase,
    ],
    imports: [
      // ...
        //flamelinkApp,

        AngularFireModule.initializeApp(firebaseConfig),
        AngularFireDatabaseModule, AngularFireAuthModule,
       // ...
    ],
   // ...
})

export class AppModule { }
```

When I try to access a page that uses Flamelink, I get [the following error](https://1drv.ms/i/s!Ahy59PyXdZAchWwG_bE6uVHBuVpp). Basically it says that I'm not passing the config options properly but I don't know what's missing.
Any help?

Here is the target page code, if anyone is interested:

**home.ts**
```js
import flamelink from 'flamelink';

export class HomePage{

  constructor(public navCtrl: NavController, public navParams: NavParams, public app: flamelink) {

    app.content.get('products')
  .then(products => console.log('All of your products:', products))
  .catch(error => {}
  );
  }
```

The **home.html** page has nothing.

**Comment by jperasmus** [comment]
Hi @DovahBrownies,

Thanks for the kind words and giving Flamelink a spin.
Two things quickly:

- The link to the error message doesn't seem to work anymore
- Instead of using `AngularFireModule.initializeApp` to initialize your app, you will need to use `firebase.initializeApp`. Alternatively, you can pass your `firebaseConfig` object directly into the `flamelink()` that will create the Firebase app instance for you under the hood.

I am not personally very familiar with Angular and I know one of my colleagues had a few challenges with getting it to work, but ended up just creating a small utility that exports the Flamelink app instance for him to use throughout his app.

Please try instantiating the app with either `firebase` or passing the config directly into `flamelink`. If that doesn't work and I can try and put you in contact with my colleague that might be able to assist with the Angular specific questions.

**Comment by DovahBrownies** [comment]
@jperasmus Sorry about that; My OneDrive was accidentally wiped and I just finished restoring the data. The link to the error message should be working now. I will try your suggestion (though I'm sure I already tried that) and I will let you know how things go!

**Comment by DovahBrownies** [comment]
I have done what you said:
```ts
// For flamelink -- https://flamelink.github.io/flamelink/#/getting-started
    const firebaseApp = firebase.initializeApp(firebaseConfig); //Try doing firebase.initialize...
    **const flamelinkApp = flamelink(firebaseConfig);**
```
And in the `imports:` under `@NgModule`:
```ts
  imports: [
        BrowserModule,
        HttpModule,

        flamelinkApp,
        
        AngularFireModule.initializeApp(firebaseConfig),
        AngularFireDatabaseModule, AngularFireAuthModule,
        IonicModule.forRoot(MyApp),
    ],
```

This gives the error: `Error: Unexpected value 'ProjectName' imported by the module 'AppModule'`

**Comment by DovahBrownies** [comment]
@jperasmus 
![flamelink](https://user-images.githubusercontent.com/35106956/34676014-ff563026-f493-11e7-8fb5-79467b11e332.png)

So the good news is that I don't get an environment break error anymore, and there doesn't seem to be an error caught by `.catch(console.error);`.
Though there is this eerie error message that displays before the environment loads.

Console does output `All of your products: null` but that is most probably because most probably didn't create the content, in the CMS, correctly; Forgive me as this is the first time I've worked with a CMS.

**Comment by jperasmus** [comment]
Whoop! It is at least a step in the right direction!

Flamelink tries to internally use the Firebase Database service. I am not familiar with AngularFire but I think we need to explicitly set the `AngularFireDatabase` module for it to work.

Try importing the following in `app.module.ts`:

```
import { AngularFireDatabaseModule, AngularFireDatabase } from 'angularfire2/database';
```

and add `AngularFireDatabaseModule` to the `imports` array and `AngularFireDatabase` to the `providers` array.

**Comment by DovahBrownies** [comment]
I have already imported:
```ts
import { AngularFireDatabaseModule } from 'angularfire2/database';
import { AngularFireDatabase, FirebaseListObservable } from "angularfire2/database-deprecated";
```
And already declared `AngularFireDatabaseModule` in `imports`
and `AngularFireDatabase` in `providers`

**Comment by jperasmus** [comment]
Ah, okay, I thought you might've used the bare minimum example that I gave you. Can you try with the example I gave you first (without all the extra goodies), just to reduce the number of variables that can go wrong?

**Comment by DovahBrownies** [comment]
Ok so after some tinkering, I'm not getting the error any longer.
My imports:
```ts
import { AngularFireDatabaseModule } from 'angularfire2/database';
import { AngularFireAuthModule, AngularFireAuth } from 'angularfire2/auth';
import { AngularFireModule, FirebaseAppProvider } from 'angularfire2';
import * as firebase from "firebase";
import { AngularFireDatabase, FirebaseListObservable } from "angularfire2/database-deprecated";

import flamelink from 'flamelink';
import { FlamelinkService } from '../services/flamelink-service';
```
Initialized flamelink as such:
```
// For flamelink -- https://flamelink.github.io/flamelink/#/getting-started
    const firebaseApp = firebase.initializeApp(firebaseConfig); //Try doing firebase.initialize...
    const flamelinkApp = flamelink({ firebaseApp });
```
`providers`:
`FlamelinkService, AngularFireDatabase`

`imports`:
`AngularFireModule.initializeApp(firebaseConfig), AngularFireDatabaseModule, AngularFireAuthModule,`

And **poof**! No more errors.
Will be tinkering with this further; just need to figure out how to actually use the CMS for testing purposes.

**Comment by jperasmus** [comment]
Okay, hoping then with you that it is working. Feel free to reach out on Slack if you have questions about the CMS itself.

**Comment by DovahBrownies** [comment]
@jperasmus Sorry for the bother, but I've logged into Slack and am ready to contact you concerning some questions I have about using the CMS for a large project. Can I have your UID, username or any form of identification that will help me message you on that platform?
Thanks!

**Comment by jperasmus** [comment]
Apologies for the delay, my Slack handle is just `jp`. Also, feel free to post any questions in the `#community-support` channel, because they might be useful to others as well.

I'm going to close this issue off for now.
