### ISSUE TITLE
Unable to retrieve file object for the entry

### ISSUE THREAD

**Issue by lukabartolicFS** [flamelink/flamelink#50]
A `populate` property of `  enables fields to be populated with their content for each entry. In case of having `media` type of field containing a file, it should replace the file ID with an object containing all the files data including a url property which is the URL to the file in the storage bucket.

However, following example code retrieves **form** entries where each entry contains a photo defined by `storyPhoto` property:

```
app.content.get('entries', {populate: true})
            .then(entries => {
                console.log(entries);
            })
            .catch(error => console.error(error));
```
Entry value of media property `storyPhoto` is set to `metadata.customMetadata.flamelinkFileId` (retrieved by uploading a file previously):
`data[fieldName] = uploadTask.metadata.customMetadata.flamelinkFileId;`
_=> storyPhoto: "1548750716541"_

Aforementioned `get()` method returns exception: 
`Something went wrong while retrieving all the content. Details: Error: [FLAMELINK] The "storyPhoto" field does not seem to be a valid media property.`

**Fact:**
The file was uploaded correctly on form submission, stored in Firebase storage and can be retrieved using `getFile()` method by passing `flamelinkFileId` parameter.
**Assumption:**
The file was referenced wrongly for the `storyPhoto` property - different value should be defined instead of using `flamelinkFileId` value.
**Question:**
Due to the fact there is no clear documentation on this matter (or I couldn't find it), what value must be defined for media property of **form** schema type so that the file object along with URL could be retrieved by calling `get()` method and passing `{populate: true}`?

P.S. I like the product and like the way it develops!

**Comment by jperasmus** [comment]
Hi @lukabartolicFS 

Thanks, I will take a look and get back to you.

**Comment by jperasmus** [comment]
That error is thrown when the value is not an array. So instead of this:

```
data[fieldName] = uploadTask.metadata.customMetadata.flamelinkFileId;
```

It should be:
```
data[fieldName] = [uploadTask.metadata.customMetadata.flamelinkFileId];
```

Can you try and let me know if it works?

**Comment by lukabartolicFS** [comment]
> That error is thrown when the value is not an array. So instead of this:
> 
> ```
> data[fieldName] = uploadTask.metadata.customMetadata.flamelinkFileId;
> ```
> It should be:
> 
> ```
> data[fieldName] = [uploadTask.metadata.customMetadata.flamelinkFileId];
> ```
> Can you try and let me know if it works?

This works, I would suggest putting this as a note in the documentation, as there might be other ones trying to achieve the same.

Thanks for your quick help and resolution!

**Comment by jperasmus** [comment]
Cool, glad it worked for you. I'll update the docs with this.
