### ISSUE TITLE
Populating content media with specific size

### ISSUE THREAD

**Issue by lukabartolicFS** [flamelink/flamelink#51]
Is it possible to apply filter to media files (images) so that images are automatically appended to the content with specific size option?

Would using something similar to this work?

```
app.content.get('blog-posts', {
  populate: [
    {
      field: 'postImage',
      size: {
           width: 240
      }
    }
  ]
});
```

Thanks!

**Comment by jperasmus** [comment]
Hi @lukabartolicFS 

That looks like it could work. You might need to specify the whole `size` object like this:
```
{
    width: 240,
    height: 9999,
    quality: 0.75
  }
```

Can you try this with a size that exists?

**Comment by lukabartolicFS** [comment]
Hi @jperasmus 

Thanks for this. However, this still returns only the file ID instead of file object. 
My entry object is following:
```
object: {
    fieldGroup1 {
        prop1: "",
        prop2: "",
       ...
       postImage: ["flamelinkFileId"]
    }
    fieldGroup2 {
        ...
    }
}
```

I tried wrapping `postImage` into `fieldGroup1` populate object as well (as relation) but still got only ID in response instead of the object:
```
{populate: [{
            field: "fieldGroup1",
            populate: [{
                field: "postImage",
                size: {
                    width: 240,
                    height: 9999,
                    quality: 1
                }
            }]
        }]}
```

I expect to get object for `postImage`. Any ideas? Thank you!

**Comment by jperasmus** [comment]
Okay, I see your image field is inside a field group field.

Can you try this:

```
{
  populate: [
    {
      field: "fieldGroup1",
      subFields: [
        {
          field: "postImage",
          size: {
            width: 240,
            height: 9999,
            quality: 1
          }
        }
      ]
    }
  ]
}
```

**Comment by lukabartolicFS** [comment]
@jperasmus thanks, you are right. I don't know how I missed the part with `subFields`. It worked with specifying `width` for `size` only as well.

**Comment by ngmiduc** [comment]
I was wondering, if this syntax is also working for `"flamelink": "^1.0.0-alpha.19"` ?

**Comment by MLoth** [comment]
> I was wondering, if this syntax is also working for `"flamelink": "^1.0.0-alpha.19"` ?

Yes, works for me.

**Comment by jperasmus** [comment]
This should also work for the new SDK, @ngmiduc 

If it doesn't, can you please open an issue on that repo so that it can be looked at?
