### ISSUE TITLE
app.content.get gives back null

### ISSUE THREAD

**Issue by balzss** [flamelink/flamelink#52]
Just started out with flamelink and when I try to get the content with `app.content.get('schemaId')` it returns null in the promise but it doesn't fail. Do I have to use something else instead of the schema id? I try anything I could think of.

**Comment by jperasmus** [comment]
Hi @balzss thanks for trying out Flamelink. The `'schemaId'` should be the Schema ID/key for an existing schema with content. Which schemas have you set up already?

**Comment by lukabartolicFS** [comment]
@balzss try switching your database type from Firestore Cloud to Realtime Database (change it in your Flamelink settings, update app code and config, set appropriate rules in Realtime Database in Firebase) and see if you get expected result.

**Comment by balzss** [comment]
@jperasmus I've tried the blog post collection example
@lukabartolicFS I did all the things you mentioned but I'm still getting null

**Comment by balzss** [comment]
Ok, so it seems like when I changed it to realtime database my schemas has dissapeared which I didn't notice at the time. Now I created them again and the API is working fine. Thanks for helping me out and sorry for not seeing such an obvious thing :)

**Comment by jperasmus** [comment]
No problem, that can happen very easily.

**Comment by Bickson** [comment]
this is happening to me, can't seem to solve it. very frustrating to get null and no errors while I can see the content in my DB.

**Comment by jperasmus** [comment]
@Bickson a few things you can check:

- which database are you using in the Flamelink app (RTDB or Firestore)?
- which database are you using in the SDK?
- which environment and language are you using? (the default?)
- do you have content for the specific schema key you are querying for?
