### ISSUE TITLE
What is the purpose for separate type - forms?

### ISSUE THREAD

**Issue by alex-belyaev** [flamelink/flamelink#57]
Hi, was trying to create simple "contact us" form and found that type forms don't have any difference with usual content type, except type name. To create something like article on frontend you need to create form and send data to flamelink, same for forms. Please correct if i'm wrong, forms are just to separate them in admin panel, correct? Or maybe i didn't look good enough?

**Comment by gitdubz** [comment]
Hi @alex-belyaev you are 100% correct, there is no difference in behavior but there is the added option to "View" the form data in plain text when it is of type "Form"

https://cl.ly/494505ee4dcc

As an aside, when we roll out the webhook feature, a filter can be applied using the type "form" in this case, to trigger integrations with other services like sending an email when a new form entry is entered, etc.

**Comment by alex-belyaev** [comment]
@gitdubz thanks for quick reply, now its clear
