### ISSUE TITLE
Sorting content in flamelink cms via date

### ISSUE THREAD

**Issue by shaunnez** [flamelink/flamelink#58]
Is it possible to get the content in the flamelink cms to have filters by the metadata (datecreated date modified)

**Comment by jperasmus** [comment]
That is a very good question/suggestion. It is not currently possible, but we can look at how we can do that.

**Comment by NiklasMencke** [comment]
This is open since 1 year and a feature that's highly needed. It will always be necessary to sort content based on creation date in a CMS. please follow up on this

**Comment by choffa** [comment]
Any updates on this? Would be really convenient to sort by create/edit date when we have articles in the hundreds.

**Comment by gitdubz** [comment]
Hi @choffa this is in the works, and is part of a larger feature to customise which columns should be shown on the data grid itself as opposed to configuring it via the schema builder - we are aiming to have this released before the end of Q4.

**Comment by gitdubz** [comment]
A new feature has been released to allow toggling which columns to show/hide.
This will allow you to show the create & last updated columns to filter/sort on.
