### ISSUE TITLE
troubles with app.content.get element with id

### ISSUE THREAD

**Issue by ngmiduc** [flamelink/flamelink#60]
Hi,

I am going to have troubles while fetching app.content with a specific ID, 
l
ike: app.content.get("contentScheme", id-of-specific-entry") 

I still get the entire list of all entries in that Scheme.

àI am using
"firebase": "^6.2.0" with Cloud Firestore Database,
"flamelink": "^1.0.0-alpha.19",

in VueJs

**Comment by jperasmus** [comment]
Hi @ngmiduc 

It looks like you are using the new alpha version of the JavaScript SDK, but using the older SDK's syntax.

You will either have to use the older SDK with version `0.19.13` or you can use the new alpha SDK, but then you'll have to use the newer syntax. The documentation for the new SDK is [here](https://flamelink.github.io/flamelink-js-sdk/#/)
