### ISSUE TITLE
vuex mutating state outside mutations

### ISSUE THREAD

**Issue by ngmiduc** [flamelink/flamelink#61]
Hi,
I getting a really strange error in my Vue project using flamelink. I was wondering how the data in `app.content.get` is bound in the variables. I need to fetch data with flamelink multiple times.

in my vuex state:

```
state: {
    loading: false,
    content: []
},
mutations: {
     setLoading(state, value) {
         state.loading = value
    },
     setState(state, d) {
          state.content = d
    },
actions: {
    async getData({ commit }) {
      commit("setLoading", true)
      ...
      let firstRequest = await app.content.get("content")
      ...
      let secondRequest = await app.content.get("content") -> error 
      ...
      commit("setState", content) -> causes error
      commit("setLoading", false)
    }
}
```

Error with the second request:
```
[Vue warn]: Error in callback for watcher "function () { return this._data.$$state }": "Error: [vuex] do not mutate vuex store state outside mutation handlers."
(found in <Root>)
```

I do not know why my state gets modified outside mutation handlers in this case...

I am using
"firebase": "^6.2.0" with Cloud Firestore Database,
"flamelink": "^1.0.0-alpha.19",
in VueJs

**Comment by jperasmus** [comment]
Hi @ngmiduc 

Not sure yet if there is more to this issue, but as a first step, can you look at my answer on your [previous issue](https://github.com/flamelink/flamelink/issues/60) and make sure you're using the correct SDK version with the right syntax.

Once you've got that sorted, let's see if there is another issue here.

**Comment by ngmiduc** [comment]
Thanks for the answer on the other issue. I did not notice that there was a new syntax. I missed that doc. It works now with the new syntax.

So checked again the code and figured out that this issue is not related to flamelink. I could solve it. I still don t know why the values get referenced but in the end I just created a deepClone object with lodash and it works.
