### ISSUE TITLE
Error: [FLAMELINK] The Database service is not available

### ISSUE THREAD

**Issue by NovaLogicDev** [flamelink/flamelink#62]
I have a js file that initializes firebase, it is linked in the head of index.html

initFirebase.js
```javascript
var firebaseConfig = {
    apiKey: "XXXXXXXXXX",
    authDomain: "XXXXXXXXXX.firebaseapp.com",
    databaseURL: "https://XXXXXXXXXX.firebaseio.com",
    projectId: "XXXXXXXXXX",
    storageBucket: "XXXXXXXXXX.appspot.com",
    messagingSenderId: "XXXXXXXXXX",
    appId: "XXXXXXXXXX"
};
// Initialize Firebase
firebaseApp = firebase.initializeApp(firebaseConfig);
globalThis.fBaseCfg = firebaseConfig```

index.html `<body>`
```javascript
<!-- FlameLink Src -->
  <script src="//unpkg.com/flamelink/dist/flamelink.js"></script>
  <script>
    console.log(globalThis.fBaseCfg)
    var app = flamelink(globalThis.fBaseCfg)
  </script>
```

In the devtools, the following output appears

```
{apiKey: "XXXXXXXXXX", authDomain: "XXXXXXXXXX.firebaseapp.com", databaseURL: "https://XXXXXXXXXX.firebaseio.com", projectId: "XXXXXXXXXX", storageBucket: "XXXXXXXXXX.appspot.com", …}apiKey: "XXXXXXXXXX"appId: "v"authDomain: "XXXXXXXXXX.firebaseapp.com"databaseURL: "https://XXXXXXXXXX.firebaseio.com"messagingSenderId: "XXXXXXXXXX"projectId: "XXXXXXXXXX"storageBucket: "XXXXXXXXXX.appspot.com"__proto__: Object


universalModuleDefinition:1 Error: [FLAMELINK] The Database service is not available. Make sure the "databaseURL" property is provided.
    at t.default (universalModuleDefinition:1)
    at Object.ref (universalModuleDefinition:1)
    at Object.subscribeRaw (universalModuleDefinition:1)
    at Object.subscribe (universalModuleDefinition:1)
    at u (universalModuleDefinition:1)
    at (index):39
```

**Comment by jperasmus** [comment]
Hi @NovaLogicDev 

How are you importing Firebase? Depending on the version of Firebase you are using, you might be importing the whole Firebase SDK (including the `database` service) or you will need to import the `app` module plus any additional services you will be using.

On a second point, it is recommended to initialize the Flamelink app by passing it the `firebaseApp` instance. This will be the only supported initialization in the future.

**Comment by NovaLogicDev** [comment]
Thanks, @jperasmus 

I added the firebase database service module and then changed over to passing it the `firebaseApp` instance, this time the error is:
```
universalModuleDefinition:1 Uncaught Error: [FLAMELINK] The following config properties are mandatory: "apiKey", "authDomain", "databaseURL", "projectId"
```
I swapped back over to using the config and the error appears to resolve.
I then added code to try to pull some content
```javascript
app.content.get('blogPosts')
      .then(blogPosts => console.log('All the blog posts:', blogPosts))
      .catch(error => console.error('Something went wrong while retrieving all the content. Details:', error));
```
This code then returned the error referenced in issue #45 
These are the realtime db rules
```
{
  "rules": {
    "flamelink": {
      ".read": "auth != null",
      ".write": "auth != null",
      "users": {
        ".indexOn": ["email", "id"]
      }
    }
  }
}
```

**Comment by jperasmus** [comment]
Thanks for the info. When you passed the `firebaseApp` instance, did you pass it as `flamelink(firebaseApp)` or `flamelink({ firebaseApp })`? The second one is the correct way, but it is fine if you want to use the other approach for now if you are going to use this SDK for the Realtime DB.

If you are receiving the error in #45 it is most likely because of your permission setup. The permissions you have set basically allows read and write actions for logged in (authenticated) users. I assume, when you are running your query, you are not logged in?

Here is an article that goes into more detail regarding setting Firebase RTDB rules for Flamelink: https://dev.to/jperasmus/how-to-set-firebase-security-rules-for-your-flamelink-project-23fn

**Comment by NovaLogicDev** [comment]
dev tools reports that I am logged in, but I have had issues with this before, I'm reading your post on permissions now and I'm making productive progress, so It would appear the issue so far is solved. Furthermore, I tried passing the `firebaseApp` instance both with and without braces and the config error persisted.

**Comment by jperasmus** [comment]
Sounds like you are making good progress. Make sure that if you need authed access, that you first log your user in before initializing the Flamelink app, because the Schemas precache will run during startup. (The new SDK does this more lazily, so it isn't an issue).
