### ISSUE TITLE
Flamelink with react native

### ISSUE THREAD

**Issue by Bickson** [flamelink/flamelink#63]
Hi, is it possible to use flamelink as a full blown cms for a react-native app? if so, how do I add a project on app.flamelink.io? what would be my "Firebase Web Application Connection Code".

Grateful for all help I can get (even if it is "no it cannot be done").

**Comment by jperasmus** [comment]
Hi @Bickson, thanks for your question. It is definitely possible to use Flamelink with React Native. Like most things on the web, you have a couple of options. What is important to know is that Flamelink stores all the content in Firebase (Real-time DB, Cloud Firestore, Storage Bucket & Authentication) services. This means anything that you are used to using to retrieve content from these services, you can still use. You use Flamelink to manage the content, and then it gets out of your way when you implement your app.

Another option is to use one of our JavaScript SDK's. The one you created this issue on is the existing/older SDK that only supports the Real-time DB. Our newer SDK is currently in alpha but supports Cloud Firestore if that is what you will be using.

Our SDK's are aware of your environment, locale, etc, but it only gives you Flamelink-specific content and services. Another great package is https://rnfirebase.io/, which is a very mature solution for React Native specifically.

I hope this gives you some ideas.

**Comment by Bickson** [comment]
all good, thank you!
what should I add to "Firebase connection detail"? `Firebase Web Application Connection Code`

**Comment by jperasmus** [comment]
Open the Firebase console, select your project and then follow this screen recording: https://app.flamelink.io/how_to_connection.3ef56f0.gif

The code snippet that you copy is the `Firebase Web Application Connection Code`.

**Comment by Bickson** [comment]
yes, just me being stupid!
thanks!
