### ISSUE TITLE
getting null from app.content

### ISSUE THREAD

**Issue by Bickson** [flamelink/flamelink#64]
Hi, I'm only getting null from firelink when trying to get content
![Screenshot 2019-06-24 at 15 04 29](https://user-images.githubusercontent.com/946680/60021367-2dd77f80-9692-11e9-939f-203ea8c84e46.png)
![Screenshot 2019-06-24 at 14 56 28](https://user-images.githubusercontent.com/946680/60021372-2fa14300-9692-11e9-9a82-91d9f41239d4.png)

I've tried to initiate app with `const firebaseApp = firebase.initializeApp(firebaseConfig)` and with native app `const firebaseApp = firebase.apps[0]`

**Comment by gitdubz** [comment]
Hi, 👋 

Have you entered any content for the schema?

**Comment by Bickson** [comment]
yes box :)
![Screenshot 2019-06-24 at 16 21 10](https://user-images.githubusercontent.com/946680/60026597-1e5d3400-969c-11e9-9008-e4cc806a5367.png)
I can see that flamelinks adds the content to my realtime DB but I can't seem to get anything out using flamelink

**Comment by gitdubz** [comment]
Can I just check which version of the SDK are you using?

**Comment by Bickson** [comment]
it was my problem, sorry if I came across rude!
I inspected the app in `firebase.apps` and it was pointing to an old "staging"-endpoint, don't know why really. I just cleaned everything and reinstalled everything and it started to worked.
thank!
