### ISSUE TITLE
Can't find variable: Symbol

### ISSUE THREAD

**Issue by Bickson** [flamelink/flamelink#65]
Hi, Im having a weird error.
![device-2019-06-28-140718](https://user-images.githubusercontent.com/946680/60341213-10febd00-99ae-11e9-8ae9-f41220aa1d66.png)
note! that this only occurs when I'm NOT debugging js remotely.
![Screenshot 2019-06-28 at 14 08 41](https://user-images.githubusercontent.com/946680/60341286-460b0f80-99ae-11e9-9784-08c198e7c561.png)
Anyone else had this experience?

**Comment by Bickson** [comment]
I solved it by adding https://github.com/react-native-community/jsc-android-buildscripts#how-to-use-it-with-my-react-native-app
seems like mobX had similar issue

**Comment by jperasmus** [comment]
This for logging this, I'm sure it will be useful for others.
