### ISSUE TITLE
Media will not populate

### ISSUE THREAD

**Issue by PeteyRev** [flamelink/flamelink#66]
I am not able to get my media fields populate for a single type schema. The structure looks like:
![2019-07-12_2013](https://user-images.githubusercontent.com/5169882/61165088-92dc0380-a4e1-11e9-81fb-bd666cb2329a.png)

and my code is:

```
  async asyncData({ app }) {
    try {
      const home = await app.flamelink.content.get(
        { schemaKey: 'homePage' },
        { populate: ['cardImage'] }
      )
      return { home }
    } catch (err) {
      console.log(err)
      return { products: [] }
    }
  }
```

The response I am getting is:
![card](https://user-images.githubusercontent.com/5169882/61165122-e2baca80-a4e1-11e9-8c10-145b9e14eeec.png)

**Comment by jperasmus** [comment]
Hi @PeteyRev 

What type of field is `homeCards`? Is it a repeater? Based on your query, you are trying to populate a field named `cardImage` from the root of your entry, but that does not exist.

Also, which version of the SDK are you using? This repo for which you created the issue is the older SDK, but the syntax you're using seems to be for the newer SDK found [here](https://github.com/flamelink/flamelink-js-sdk).

**Comment by PeteyRev** [comment]
Hi @jperasmus, yes it is a repeater, and yes, this is the newer sdk `1.0.0-alpha.19` I didn't realize this was the wrong repo, my bad.

I can move this to the newer repo but it seems like this is not an flamelink issue - however I still am not getting the correct fields even targeting the repeater sub field:

```
      const home = await app.flamelink.content.get(
        { schemaKey: 'homePage' },
        {
          populate: [
            {
              field: 'homeCards',
              subFields: ['cardImage']
            }
          ]
        }
      )
```
Is this not the correct syntax?

**Comment by jperasmus** [comment]
Hi, sorry, this one slipped by. For the newer SDK, there is now only one single object for all the arguments passed to the SDK methods.

It will be something like this instead:

```
const home = await app.flamelink.content.get(
  {
    schemaKey: 'homePage',
    populate: [
      {
        field: 'homeCards',
        subFields: ['cardImage']
      }
    ]
  }
)
```

**Comment by PeteyRev** [comment]
@jperasmus awesome, thanks!
