### ISSUE TITLE
I have some problems when user click URL ,but user cannot get user response from flamelink

### ISSUE THREAD

**Issue by lagmanzaza** [flamelink/flamelink#7]

**Comment by lagmanzaza** [comment]
I use VueJS

**Comment by jperasmus** [comment]
Hi @lagmanzaza, can you elaborate a bit on the problem? If you are talking about images not available to your front-end, please double check your Firebase Storage permissions to make sure that the files are available for your use case. If you need your images to be available for non-logged in users, then make sure that the "read" permissions allow for that. Something like this:

```
service firebase.storage {
  match /b/{bucket}/o {
    match /{allPaths=**} {
      allow read, write: if request.auth != null;
    }
    match /flamelink/{allPaths=**} {
      allow read;
      allow write: if request.auth != null;
    }
  }
}
```

Also see [this issue](https://github.com/flamelink/flamelink/issues/1) for a bit more information around Flamelink vs Firebase permissions.

**Comment by lagmanzaza** [comment]
`service firebase.storage {
  match /b/{bucket}/o {
    match /{allPaths=**} {
      allow read, write;
    }
  }
}
`

I test with this rule but it does not work.

**Comment by jperasmus** [comment]
Okay, out of interest, please try with: `service firebase.storage { match /b/{bucket}/o { match /{allPaths=**} { allow read; allow write; } } }`

If that doesn't work, please paste the error message that you are getting.

**Comment by lagmanzaza** [comment]
It's not work and No error message

I think that is my mistake with Vue so I will try to find the bug 

thank you

**Comment by jperasmus** [comment]
Okay, good luck 👍🏼
