### ISSUE TITLE
Add quickview to content editor

### ISSUE THREAD

**Issue by elarb** [flamelink/flamelink#8]
When adding new content with the content editor, the already stored content is shown like this:

![image](https://user-images.githubusercontent.com/18485279/34905623-4618b34a-f85d-11e7-83f2-18c4e4e4ad20.png)

It would be a great improvement to let the user create a quick view of the content, e.g. a couple of fields that should be displayed in the editor. 

An example for a product: Small image, title, SKU, price, stock.

Maybe a select (letting the user select a couple of fields for the quickview) in the corresponding "Schema Details" form would be an option? The fields able for selection should be limited (only text, numbers, images, etc.) to avoid having to deal with complex fields.

**Comment by jperasmus** [comment]
Hi @elarb,

Thanks for getting in touch. This functionality is already possible from within the CMS. If you go into the Schema editor and click on an individual field, there is a switch to enable that particular field to be visible on the summary view.

Can you try that out and let me know if it helps?

**Comment by elarb** [comment]
Yes it worked. I overlooked that one, great!
