### ISSUE TITLE
Pulling data from Flamelink in ReactNative is "often" very slow.

### ISSUE THREAD

**Issue by fabien-lg** [flamelink/flamelink#85]
Hello!

I am using the Flamelink SDK on React Native on Android (although I am not sure if it's relevant to the issue). I used [React Native Firebase](https://invertase.io/oss/react-native-firebase/).

The loading time, to get a collection, are very variant, sometimes it takes 10 seconds, sometimes more than 60 seconds.

I guess that it may be related to the local cache, as usually the initial cold loading times are much faster than a reload of the app.

## What I have tried
  - Shrinking down the amount of data collected using the `fields` parameter - no change
  - Sequentially loading the collections instead of pulling them all at the same time - no change

## Specifications
  - Version: `^1.0.0-alpha.26`
  - Platform: Android
  - Framework: React Native

## Expected Behavior
  - Consistent loading time when using the `get` function

## Actual Behavior
  - Using the `get` function on a small collection (~10 elements with 3 relational elements inside the schema) sometimes takes 10 seconds, sometimes more than 60 seconds

**Comment by jperasmus** [comment]
Hi there, @fabien-lg 

I don't understand 100%, did you also try [React Native Firebase](https://invertase.io/oss/react-native-firebase/)? How was the performance for the queries then?

**Comment by fabien-lg** [comment]
Hi @jperasmus ,

Yes, I am using React Native Firebase and this is when the performances started to drop.

Thanks!

**Comment by jperasmus** [comment]
Thanks for clarifying, Fabien. I would recommend trying out a query with [Firebase's JavaScript SDK](https://firebase.google.com/docs/web/setup) directly to compare the performance. This will help you figure out if the performance issue is with the React Native Firebase package or if it is slow across the network to Firebase itself.

The Flamelink CMS app persists all the content you manage directly in Firebase (either the realtime DB or Cloud Firestore + your storage bucket). You are free to retrieve the content for your app in any way that Firebase supports. You can use React Native Firebase like you're doing, or you can use the Firebase JS SDK, the Firebase REST API, our Flamelink JS SDK or any other means.

If you find that the performance issue is with React Native Firebase or Firebase itself, I would recommend opening a ticket with them directly. We are not directly affiliated with them.

Hope that makes sense.
