### ISSUE TITLE
Filtering data from any collection (schema) not possible?

### ISSUE THREAD

**Issue by NiklasMencke** [flamelink/flamelink#86]
Hi, 

I'm using the SDK in combination with React Native and React Native Firebase and using the Flamelink SDK Version `flamelink": "^1.0.0-alpha.27`.
I want to retrieve **multiple** entries from a certain collection/schema based on one filter value I provide for a certain field of the schema. 

So let's say I have the schema/collection 'recipes', which contains recipes with following fields: 'title', 'description', 'type'. 

**Now I want to retrieve all the recipes that fulfill the condition type='xyz'.** 

According to the documentation I would assume it's done like this:
`const recipes = await flamelinkApp.content.getByField('recipes', 'type', 'xyz');
  console.log('All recipes:', recipes);`

**which is throwing following error: 
`[Error: firebase.firestore().collection().where(*) 'fieldPath' must be a string or instance of FieldPath.]`**

Another way that I tried is: 
`        const recipes = await flamelinkApp.content.get('recipes', {
          orderByChild: 'type',
          equalTo: 'xyz',
        });`

which doesn't fail but just r**eturns ALL the recipes**, instead of filtering for 'xyz'. 

Can you please tell me if this is the correct approach or if filtering is just not supported?

Thanks!

**Comment by jperasmus** [comment]
Hi, which version of the SDK are you using?

**Comment by NiklasMencke** [comment]
Hi,
using: `"flamelink": "^1.0.0-alpha.27"`

**Comment by NiklasMencke** [comment]
I just checked again and apparently I was using the old documentation (=old syntax) while using the new sdk. 

Doing the query like this solved it for me:
` const recipes = await flamelinkApp.content.getByField({
          schemaKey: 'recipes',
          field: 'type',
          value: 'xyz',
        });`

and it worked now!

**Comment by jperasmus** [comment]
Awesome, I'm glad you got it working! If you need to perform more advanced filtering, you can take a look at the `filters` property. With that, you can filter on multiple properties.

**Comment by ngmiduc** [comment]
Hi,

I am using `"flamelink": "^1.0.0-alpha.30"` and I get some troubles of querying data again:
I used the above syntax but I didn't work on my side:

```
        const response = await app.content.get({
          schemaKey: "companies",
          field: "companyName",
          value: "Cardio Choc",
          populate: [
            {
              field: "logo",
              size: {
                width: 375,
                height: 9999,
                quality: 1
              }
            }
          ]
        })
```

It returns me all entries.
I am not sure what is wrong here.
