### ISSUE TITLE
Validation Rules for empty fields

### ISSUE THREAD

**Issue by EirikOsnes** [flamelink/flamelink#88]
When adding new fields, we have found the validation rules to be a good idea. However! When setting validation rules on non-required fields, the validation rule will throw errors.

Would it be possible to allow adding validation rules to a field, and only check it if it is non-empty? If empty fields are to be disallowed, it should be as simple as also adding a Required validation rule.

For example, we want to add a email field for contact info, but where this email is not available it should be left blank. We would like to validate that it is a valid email before saving, but leaving it empty should also be allowed. However, adding the "Email" Validation Rule throws when the Field is empty, even though no "Required" Rule is set.

**Comment by jperasmus** [comment]
Hi @EirikOsnes 

Thanks for the question. In this case, your best bet would be to use the Regular Expression pattern to optionally match your email address.

You can look at a regex pattern like these: https://stackoverflow.com/questions/5063977/regex-empty-string-or-email
