### ISSUE TITLE
Reuse and bind schema's

### ISSUE THREAD

**Issue by elarb** [flamelink/flamelink#9]
Especially with a document-orient database, it's useful to repeat data, making reading easier and more importantly, decrease the number of database queries required.

Therefore, it would be a great to have reusable schema's, and maybe even have the option to (partly) two-way bind different parts of the data.

If this is already possible, please let me know!

**Comment by jperasmus** [comment]
This sounds interesting. Do you mind elaborating a bit so that I am sure I understand exactly what you mean and how you would like to use it?
