### ISSUE TITLE
permission_denied for files

### ISSUE THREAD

**Issue by joshbell** [flamelink/flamelink#97]
Greetings,

I'm getting the following error from the flamelink sdk:
"Something went wrong while retrieving the folders. Details: Error: permission_denied at /flamelink/media/folders: Client doesn't have permission to access the desired data."

I am currently using the getFolders() function copied from the example in the documentation [here](https://flamelink.github.io/flamelink-js-sdk/#/storage?id=getfolders).

I am using cloud firestore, which I understand at one point was not working with this SDK. I no longer see that warning so I assume it is working.  I also assume that this is an issue with my permissions, so I will paste them here:

Cloud Firestore:
`service cloud.firestore {
  match /databases/{database}/documents {
  	match /{document=**} {
    	allow read: if true;
      allow write: if request.auth.uid != null;
    }
  	match /fl_content/{content} {
    	allow read: if true;
      allow write: if request.auth.uid != null;
    }
    match /fl_users/{user} {
      allow read, write: if request.auth.uid != null;
    }
  }
}`

Storage:
`service firebase.storage {
  match /b/{bucket}/o {
    match /{allPaths=**} {
      allow read, write: if request.auth != null;
    }
    match /flamelink/{allPaths=**} {
      allow read;
      allow write: if request.auth != null;
    }
  }
}`

I've fiddled around with them but I've had no success.

This is a client-facing application  that will simply view a list of files that are uploaded in flamelink.  It requires no auth and will only be viewing and downloading files.  What are the correct permissions for this?

Thanks!

**Comment by dewetvdm** [comment]
Hi,

Can you perhaps share the code for initializing the flamelink SDK? (remember to replace actual API keys and details with xxx)

It seems like it is trying to access the RTDB and not CF.
```javascript
const app = flamelink({
  firebaseApp,
  env: 'production', // optional, defaults to `production`
  locale: 'en-US', // optional, defaults to `en-US`
  dbType: 'rtdb' // optional, defaults to `rtdb` - can be 'rtdb' or 'cf' (Realtime DB vs Cloud Firestore)
})
```

Note the `dbType` defaults to 'rtdb' and should be changed to 'cf' if not already done.

If this is not the issue we can have a look at the imported packages

**Comment by joshbell** [comment]
That resolved the issue!

I was initializing it using the example on the [Getting Started](https://flamelink.github.io/flamelink/#/getting-started) section of the docs.
`const app = flamelink({ firebaseApp });`

Specifying the dbType as 'cf' resolved the issue.

Thanks for the help!

**Comment by gitdubz** [comment]
No problem,
You can find the latest docs for the latest sdk here
https://flamelink.github.io/flamelink-js-sdk/#/getting-started

Note the Flamelink SDK has moved to
https://github.com/flamelink/flamelink-js-sdk
